{% set name = "qiskit-metal" %}
{% set version = "0.1.3" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://github.com/Qiskit/{{ name }}/archive/refs/tags/{{ version }}.tar.gz
  sha256: c252870257e57ea41fd2006c8bf85902a4e11df962960e9c924600d09642c196

build:
  script: {{ PYTHON }} -m pip install . -vv
  number: 0
  noarch: python

requirements:
  host:
    - python >=3.7
    - pip
  run:
    - python >=3.7
    - addict =2.4.0
    - descartes =1.1.0
    - gdspy =1.6.12
    - geopandas =0.12.2
    - gmsh =4.11.1
    - ipython =8.10.0
    - matplotlib-base =3.7.0
    - numpy =1.24.2
    - pandas =1.5.3
    - pint =0.20.1
    - pyaedt =0.6.46
    - pyepr-quantum =0.8.5.7
    - pygments =2.14.0
    - pyside2 =5.15.2.1
    - pyyaml =6.0
    - qutip =4.7.1
    - scipy =1.10.0
    - shapely =2.0.1
    - scqubits =3.1.0

test:
  imports:
    - qiskit_metal
  commands:
    - pip check
  requires:
    - pip

about:
  home: https://github.com/Qiskit/qiskit-metal
  summary: Qiskit Metal | for quantum device design & analysis
  license: Apache-2.0
  license_file: LICENSE.txt

extra:
  recipe-maintainers:
    - wshanks
