{% set name = "qiskit-metal" %}
{% set version = "0.5.1" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://github.com/Qiskit/{{ name }}/archive/refs/tags/{{ version }}.tar.gz
  sha256: 9557a92255b0b6e46ed3f6387dfb5fcc9cbaeb0c18d57b509eb23612efae6d12

build:
  script: {{ PYTHON }} -m pip install . -vv
  number: 0
  noarch: python

requirements:
  host:
    - python >=3.7
    - pip
  run:
    - python >=3.7
    - addict
    - descartes
    - gdspy >=1.5.2
    - geopandas
    - ipython
    - matplotlib-base
    - numpy
    - pandas
    - pint
    - pyepr-quantum >=0.8.5.7
    - pygments
    - pyside2
    - qutip
    - scipy
    - shapely
    - scqubits

test:
  imports:
    - qiskit_metal
  commands:
    - pip check
  requires:
    - pip

about:
  home: https://github.com/qiskit-community/qiskit-metal
  summary: Qiskit Metal | for quantum device design & analysis
  license: Apache-2.0
  license_file: LICENSE.txt

extra:
  recipe-maintainers:
    - wshanks
