{% set name = "qiskit-metal" %}
{% set version = "0.1.4" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://github.com/Qiskit/{{ name }}/archive/refs/tags/{{ version }}.tar.gz
  sha256: 6963f43b7364dcb8a0a2cc1c94fce326e6749fb5312cd46e2742a8498cbd3b8b

build:
  script: {{ PYTHON }} -m pip install . -vv
  number: 0
  noarch: python

requirements:
  host:
    - python >=3.7
    - pip
  run:
    - python >=3.7
    - addict
    - descartes
    - gdspy >=1.5.2
    - geopandas
    - ipython
    - matplotlib-base
    - numpy
    - pandas
    - pint
    - pyepr-quantum >=0.8.5.7
    - pygments
    - pyside2
    - qutip
    - scipy
    - shapely
    - scqubits

test:
  imports:
    - qiskit_metal
  commands:
    - pip check
  requires:
    - pip

about:
  home: https://github.com/Qiskit/qiskit-metal
  summary: Qiskit Metal | for quantum device design & analysis
  license: Apache-2.0
  license_file: LICENSE.txt

extra:
  recipe-maintainers:
    - wshanks
